spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  security:
    user:
      password: "123"

application:
  security:
    jwt:
      secret-key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days